import React from 'react';
import {
  Layers,
  Split,
  RotateCw,
  LayoutGrid,
  Image as ImageIcon,
  Images,
  Stamp,
  Lock,
  Edit3,
  Minimize2,
  Search,
  Briefcase,
  Contact,
  FileCheck,
  FileImage,
  FileText,
  QrCode,
  EyeOff,
  PenTool,
  ScanText,
  User,
  Calendar,
  ShieldCheck,
  Receipt,
  FileCheck2,
  Percent,
  Type,
  Grid,
  Contrast,
  Crop,
  FileSignature,
  FileSpreadsheet,
  GitCompare,
  FileDigit,
  Eraser,
} from 'lucide-react';
import { ToolId, ToolDefinition } from '../types';

export interface ToolItemConfig {
  id: ToolId;
  titleKey: string;
  descKey: string;
  category: ToolDefinition['category'];
  badgeText?: string;
  icon: React.ComponentType<{ className?: string }>;
  colors: {
    bg: string;
    text: string;
    lightBg: string;
    lightText: string;
    border: string;
    hoverBorder: string;
    gradient: string;
    accent: string;
  };
}

export const TOOLS_CONFIG: Record<ToolId, ToolItemConfig> = {
  merge: {
    id: 'merge',
    titleKey: 'merge',
    descKey: 'merge',
    category: 'organize',
    badgeText: 'شائع',
    icon: Layers,
    colors: {
      bg: 'bg-red-500',
      text: 'text-white',
      lightBg: 'bg-red-50 dark:bg-red-950/50',
      lightText: 'text-red-600 dark:text-red-400',
      border: 'border-red-200 dark:border-red-800',
      hoverBorder: 'hover:border-red-400',
      gradient: 'from-red-500 to-rose-600',
      accent: '#ef4444',
    },
  },
  split: {
    id: 'split',
    titleKey: 'split',
    descKey: 'split',
    category: 'organize',
    badgeText: 'شائع',
    icon: Split,
    colors: {
      bg: 'bg-amber-500',
      text: 'text-white',
      lightBg: 'bg-amber-50 dark:bg-amber-950/50',
      lightText: 'text-amber-600 dark:text-amber-400',
      border: 'border-amber-200 dark:border-amber-800',
      hoverBorder: 'hover:border-amber-400',
      gradient: 'from-amber-500 to-orange-600',
      accent: '#f59e0b',
    },
  },
  compress: {
    id: 'compress',
    titleKey: 'compress',
    descKey: 'compress',
    category: 'edit',
    badgeText: 'سريع',
    icon: Minimize2,
    colors: {
      bg: 'bg-emerald-600',
      text: 'text-white',
      lightBg: 'bg-emerald-50 dark:bg-emerald-950/50',
      lightText: 'text-emerald-600 dark:text-emerald-400',
      border: 'border-emerald-200 dark:border-emerald-800',
      hoverBorder: 'hover:border-emerald-400',
      gradient: 'from-emerald-500 to-teal-600',
      accent: '#059669',
    },
  },
  'image-to-pdf': {
    id: 'image-to-pdf',
    titleKey: 'imageToPdf',
    descKey: 'imageToPdf',
    category: 'convert',
    badgeText: 'شائع',
    icon: ImageIcon,
    colors: {
      bg: 'bg-yellow-500',
      text: 'text-white',
      lightBg: 'bg-yellow-50 dark:bg-yellow-950/50',
      lightText: 'text-yellow-700 dark:text-yellow-400',
      border: 'border-yellow-200 dark:border-yellow-800',
      hoverBorder: 'hover:border-yellow-400',
      gradient: 'from-yellow-500 to-amber-600',
      accent: '#eab308',
    },
  },
  'pdf-to-image': {
    id: 'pdf-to-image',
    titleKey: 'pdfToImage',
    descKey: 'pdfToImage',
    category: 'convert',
    badgeText: 'JPG / PNG',
    icon: Images,
    colors: {
      bg: 'bg-rose-500',
      text: 'text-white',
      lightBg: 'bg-rose-50 dark:bg-rose-950/50',
      lightText: 'text-rose-600 dark:text-rose-400',
      border: 'border-rose-200 dark:border-rose-800',
      hoverBorder: 'hover:border-rose-400',
      gradient: 'from-rose-500 to-pink-600',
      accent: '#f43f5e',
    },
  },
  'image-tools': {
    id: 'image-tools',
    titleKey: 'imageTools',
    descKey: 'imageTools',
    category: 'convert',
    icon: FileImage,
    colors: {
      bg: 'bg-cyan-600',
      text: 'text-white',
      lightBg: 'bg-cyan-50 dark:bg-cyan-950/50',
      lightText: 'text-cyan-700 dark:text-cyan-400',
      border: 'border-cyan-200 dark:border-cyan-800',
      hoverBorder: 'hover:border-cyan-400',
      gradient: 'from-cyan-500 to-blue-600',
      accent: '#0891b2',
    },
  },
  'search-text': {
    id: 'search-text',
    titleKey: 'searchText',
    descKey: 'searchText',
    category: 'search',
    icon: Search,
    colors: {
      bg: 'bg-sky-500',
      text: 'text-white',
      lightBg: 'bg-sky-50 dark:bg-sky-950/50',
      lightText: 'text-sky-600 dark:text-sky-400',
      border: 'border-sky-200 dark:border-sky-800',
      hoverBorder: 'hover:border-sky-400',
      gradient: 'from-sky-500 to-blue-600',
      accent: '#0ea5e9',
    },
  },
  edit: {
    id: 'edit',
    titleKey: 'edit',
    descKey: 'edit',
    category: 'edit',
    badgeText: 'محرر',
    icon: Edit3,
    colors: {
      bg: 'bg-blue-600',
      text: 'text-white',
      lightBg: 'bg-blue-50 dark:bg-blue-950/50',
      lightText: 'text-blue-600 dark:text-blue-400',
      border: 'border-blue-200 dark:border-blue-800',
      hoverBorder: 'hover:border-blue-400',
      gradient: 'from-blue-500 to-indigo-600',
      accent: '#2563eb',
    },
  },
  organize: {
    id: 'organize',
    titleKey: 'organize',
    descKey: 'organize',
    category: 'organize',
    icon: LayoutGrid,
    colors: {
      bg: 'bg-indigo-500',
      text: 'text-white',
      lightBg: 'bg-indigo-50 dark:bg-indigo-950/50',
      lightText: 'text-indigo-600 dark:text-indigo-400',
      border: 'border-indigo-200 dark:border-indigo-800',
      hoverBorder: 'hover:border-indigo-400',
      gradient: 'from-indigo-500 to-purple-600',
      accent: '#6366f1',
    },
  },
  rotate: {
    id: 'rotate',
    titleKey: 'rotate',
    descKey: 'rotate',
    category: 'organize',
    icon: RotateCw,
    colors: {
      bg: 'bg-orange-500',
      text: 'text-white',
      lightBg: 'bg-orange-50 dark:bg-orange-950/50',
      lightText: 'text-orange-600 dark:text-orange-400',
      border: 'border-orange-200 dark:border-orange-800',
      hoverBorder: 'hover:border-orange-400',
      gradient: 'from-orange-500 to-amber-600',
      accent: '#f97316',
    },
  },
  'stamp-remover': {
    id: 'stamp-remover',
    titleKey: 'stampRemover',
    descKey: 'stampRemover',
    category: 'edit',
    icon: FileCheck,
    colors: {
      bg: 'bg-rose-600',
      text: 'text-white',
      lightBg: 'bg-rose-50 dark:bg-rose-950/50',
      lightText: 'text-rose-600 dark:text-rose-400',
      border: 'border-rose-200 dark:border-rose-800',
      hoverBorder: 'hover:border-rose-400',
      gradient: 'from-rose-600 to-red-700',
      accent: '#e11d48',
    },
  },
  watermark: {
    id: 'watermark',
    titleKey: 'watermark',
    descKey: 'watermark',
    category: 'edit',
    icon: Stamp,
    colors: {
      bg: 'bg-purple-600',
      text: 'text-white',
      lightBg: 'bg-purple-50 dark:bg-purple-950/50',
      lightText: 'text-purple-600 dark:text-purple-400',
      border: 'border-purple-200 dark:border-purple-800',
      hoverBorder: 'hover:border-purple-400',
      gradient: 'from-purple-500 to-fuchsia-600',
      accent: '#9333ea',
    },
  },
  protect: {
    id: 'protect',
    titleKey: 'protect',
    descKey: 'protect',
    category: 'security',
    badgeText: 'أمان',
    icon: Lock,
    colors: {
      bg: 'bg-violet-700',
      text: 'text-white',
      lightBg: 'bg-violet-50 dark:bg-violet-950/50',
      lightText: 'text-violet-700 dark:text-violet-400',
      border: 'border-violet-200 dark:border-violet-800',
      hoverBorder: 'hover:border-violet-400',
      gradient: 'from-violet-600 to-purple-800',
      accent: '#6d28d9',
    },
  },
  redact: {
    id: 'redact',
    titleKey: 'redact',
    descKey: 'redact',
    category: 'security',
    badgeText: 'حجب سري',
    icon: EyeOff,
    colors: {
      bg: 'bg-stone-800',
      text: 'text-white',
      lightBg: 'bg-stone-100 dark:bg-stone-900',
      lightText: 'text-stone-800 dark:text-stone-300',
      border: 'border-stone-300 dark:border-stone-700',
      hoverBorder: 'hover:border-stone-500',
      gradient: 'from-stone-700 to-stone-900',
      accent: '#292524',
    },
  },
  sign: {
    id: 'sign',
    titleKey: 'sign',
    descKey: 'sign',
    category: 'edit',
    badgeText: 'توقيع رسمي',
    icon: PenTool,
    colors: {
      bg: 'bg-teal-600',
      text: 'text-white',
      lightBg: 'bg-teal-50 dark:bg-teal-950/50',
      lightText: 'text-teal-700 dark:text-teal-400',
      border: 'border-teal-200 dark:border-teal-800',
      hoverBorder: 'hover:border-teal-400',
      gradient: 'from-teal-500 to-emerald-600',
      accent: '#0d9488',
    },
  },
  ocr: {
    id: 'ocr',
    titleKey: 'ocr',
    descKey: 'ocr',
    category: 'convert',
    badgeText: 'ذكاء OCR',
    icon: ScanText,
    colors: {
      bg: 'bg-indigo-600',
      text: 'text-white',
      lightBg: 'bg-indigo-50 dark:bg-indigo-950/50',
      lightText: 'text-indigo-600 dark:text-indigo-400',
      border: 'border-indigo-200 dark:border-indigo-800',
      hoverBorder: 'hover:border-indigo-400',
      gradient: 'from-indigo-600 to-blue-700',
      accent: '#4f46e5',
    },
  },
  'id-photo': {
    id: 'id-photo',
    titleKey: 'idPhoto',
    descKey: 'idPhoto',
    category: 'convert',
    badgeText: '4×6 رسمي',
    icon: User,
    colors: {
      bg: 'bg-sky-600',
      text: 'text-white',
      lightBg: 'bg-sky-50 dark:bg-sky-950/50',
      lightText: 'text-sky-600 dark:text-sky-400',
      border: 'border-sky-200 dark:border-sky-800',
      hoverBorder: 'hover:border-sky-400',
      gradient: 'from-sky-500 to-cyan-600',
      accent: '#0284c7',
    },
  },
  'metadata-cleaner': {
    id: 'metadata-cleaner',
    titleKey: 'metadataCleaner',
    descKey: 'metadataCleaner',
    category: 'security',
    icon: ShieldCheck,
    colors: {
      bg: 'bg-slate-700',
      text: 'text-white',
      lightBg: 'bg-slate-100 dark:bg-slate-800',
      lightText: 'text-slate-700 dark:text-slate-300',
      border: 'border-slate-300 dark:border-slate-700',
      hoverBorder: 'hover:border-slate-500',
      gradient: 'from-slate-600 to-slate-800',
      accent: '#334155',
    },
  },
  payroll: {
    id: 'payroll',
    titleKey: 'payroll',
    descKey: 'payroll',
    category: 'business',
    badgeText: 'معتمد للرواتب',
    icon: FileSpreadsheet,
    colors: {
      bg: 'bg-emerald-600',
      text: 'text-white',
      lightBg: 'bg-emerald-50 dark:bg-emerald-950/50',
      lightText: 'text-emerald-700 dark:text-emerald-400',
      border: 'border-emerald-200 dark:border-emerald-800',
      hoverBorder: 'hover:border-emerald-400',
      gradient: 'from-emerald-500 to-green-700',
      accent: '#059669',
    },
  },
  clearance: {
    id: 'clearance',
    titleKey: 'clearance',
    descKey: 'clearance',
    category: 'business',
    badgeText: 'نهاية خدمة',
    icon: FileSignature,
    colors: {
      bg: 'bg-teal-600',
      text: 'text-white',
      lightBg: 'bg-teal-50 dark:bg-teal-950/50',
      lightText: 'text-teal-700 dark:text-teal-400',
      border: 'border-teal-200 dark:border-teal-800',
      hoverBorder: 'hover:border-teal-400',
      gradient: 'from-teal-600 to-cyan-700',
      accent: '#0d9488',
    },
  },
  invoice: {
    id: 'invoice',
    titleKey: 'invoice',
    descKey: 'invoice',
    category: 'business',
    badgeText: 'فاتورة ضريبية',
    icon: Receipt,
    colors: {
      bg: 'bg-blue-600',
      text: 'text-white',
      lightBg: 'bg-blue-50 dark:bg-blue-950/50',
      lightText: 'text-blue-700 dark:text-blue-400',
      border: 'border-blue-200 dark:border-blue-800',
      hoverBorder: 'hover:border-blue-400',
      gradient: 'from-blue-600 to-indigo-700',
      accent: '#2563eb',
    },
  },
  voucher: {
    id: 'voucher',
    titleKey: 'voucher',
    descKey: 'voucher',
    category: 'business',
    badgeText: 'قبض وصرف',
    icon: FileCheck2,
    colors: {
      bg: 'bg-purple-600',
      text: 'text-white',
      lightBg: 'bg-purple-50 dark:bg-purple-950/50',
      lightText: 'text-purple-700 dark:text-purple-400',
      border: 'border-purple-200 dark:border-purple-800',
      hoverBorder: 'hover:border-purple-400',
      gradient: 'from-purple-600 to-violet-700',
      accent: '#9333ea',
    },
  },
  'vat-calculator': {
    id: 'vat-calculator',
    titleKey: 'vatCalculator',
    descKey: 'vatCalculator',
    category: 'business',
    badgeText: '15% معتمدة',
    icon: Percent,
    colors: {
      bg: 'bg-emerald-500',
      text: 'text-white',
      lightBg: 'bg-emerald-50 dark:bg-emerald-950/50',
      lightText: 'text-emerald-700 dark:text-emerald-400',
      border: 'border-emerald-200 dark:border-emerald-800',
      hoverBorder: 'hover:border-emerald-400',
      gradient: 'from-emerald-500 to-teal-600',
      accent: '#10b981',
    },
  },
  tafqeet: {
    id: 'tafqeet',
    titleKey: 'tafqeet',
    descKey: 'tafqeet',
    category: 'business',
    badgeText: 'ريال وهللة',
    icon: Type,
    colors: {
      bg: 'bg-amber-600',
      text: 'text-white',
      lightBg: 'bg-amber-50 dark:bg-amber-950/50',
      lightText: 'text-amber-700 dark:text-amber-400',
      border: 'border-amber-200 dark:border-amber-800',
      hoverBorder: 'hover:border-amber-400',
      gradient: 'from-amber-500 to-orange-600',
      accent: '#d97706',
    },
  },
  nup: {
    id: 'nup',
    titleKey: 'nup',
    descKey: 'nup',
    category: 'organize',
    badgeText: 'توفير طباعة',
    icon: Grid,
    colors: {
      bg: 'bg-cyan-500',
      text: 'text-white',
      lightBg: 'bg-cyan-50 dark:bg-cyan-950/50',
      lightText: 'text-cyan-600 dark:text-cyan-400',
      border: 'border-cyan-200 dark:border-cyan-800',
      hoverBorder: 'hover:border-cyan-400',
      gradient: 'from-cyan-500 to-sky-600',
      accent: '#06b6d4',
    },
  },
  'pdf-grayscale': {
    id: 'pdf-grayscale',
    titleKey: 'pdfGrayscale',
    descKey: 'pdfGrayscale',
    category: 'edit',
    icon: Contrast,
    colors: {
      bg: 'bg-slate-600',
      text: 'text-white',
      lightBg: 'bg-slate-100 dark:bg-slate-800',
      lightText: 'text-slate-700 dark:text-slate-300',
      border: 'border-slate-300 dark:border-slate-700',
      hoverBorder: 'hover:border-slate-500',
      gradient: 'from-slate-500 to-gray-700',
      accent: '#475569',
    },
  },
  'image-watermark': {
    id: 'image-watermark',
    titleKey: 'imageWatermark',
    descKey: 'imageWatermark',
    category: 'edit',
    icon: Stamp,
    colors: {
      bg: 'bg-amber-600',
      text: 'text-white',
      lightBg: 'bg-amber-50 dark:bg-amber-950/50',
      lightText: 'text-amber-700 dark:text-amber-400',
      border: 'border-amber-200 dark:border-amber-800',
      hoverBorder: 'hover:border-amber-400',
      gradient: 'from-amber-600 to-orange-700',
      accent: '#d97706',
    },
  },
  'social-crop': {
    id: 'social-crop',
    titleKey: 'socialCrop',
    descKey: 'socialCrop',
    category: 'convert',
    icon: Crop,
    colors: {
      bg: 'bg-fuchsia-600',
      text: 'text-white',
      lightBg: 'bg-fuchsia-50 dark:bg-fuchsia-950/50',
      lightText: 'text-fuchsia-700 dark:text-fuchsia-400',
      border: 'border-fuchsia-200 dark:border-fuchsia-800',
      hoverBorder: 'hover:border-fuchsia-400',
      gradient: 'from-fuchsia-500 to-pink-600',
      accent: '#c026d3',
    },
  },
  'stitch-images': {
    id: 'stitch-images',
    titleKey: 'stitchImages',
    descKey: 'stitchImages',
    category: 'convert',
    icon: Layers,
    colors: {
      bg: 'bg-orange-600',
      text: 'text-white',
      lightBg: 'bg-orange-50 dark:bg-orange-950/50',
      lightText: 'text-orange-700 dark:text-orange-400',
      border: 'border-orange-200 dark:border-orange-800',
      hoverBorder: 'hover:border-orange-400',
      gradient: 'from-orange-500 to-red-600',
      accent: '#ea580c',
    },
  },
  'cv-builder': {
    id: 'cv-builder',
    titleKey: 'cvBuilder',
    descKey: 'cvBuilder',
    category: 'cv',
    badgeText: '3 نماذج احترافية',
    icon: Briefcase,
    colors: {
      bg: 'bg-blue-700',
      text: 'text-white',
      lightBg: 'bg-blue-50 dark:bg-blue-950/50',
      lightText: 'text-blue-700 dark:text-blue-400',
      border: 'border-blue-200 dark:border-blue-800',
      hoverBorder: 'hover:border-blue-400',
      gradient: 'from-blue-600 to-indigo-800',
      accent: '#1d4ed8',
    },
  },
  'cv-modern': {
    id: 'cv-modern',
    titleKey: 'cvModern',
    descKey: 'cvModern',
    category: 'cv',
    badgeText: 'العصري',
    icon: Layers,
    colors: {
      bg: 'bg-blue-600',
      text: 'text-white',
      lightBg: 'bg-blue-50 dark:bg-blue-950/50',
      lightText: 'text-blue-700 dark:text-blue-400',
      border: 'border-blue-200 dark:border-blue-800',
      hoverBorder: 'hover:border-blue-400',
      gradient: 'from-blue-600 to-indigo-700',
      accent: '#2563eb',
    },
  },
  'cv-table': {
    id: 'cv-table',
    titleKey: 'cvTable',
    descKey: 'cvTable',
    category: 'cv',
    badgeText: 'التفاعلي',
    icon: FileSpreadsheet,
    colors: {
      bg: 'bg-teal-600',
      text: 'text-white',
      lightBg: 'bg-teal-50 dark:bg-teal-950/50',
      lightText: 'text-teal-700 dark:text-teal-400',
      border: 'border-teal-200 dark:border-teal-800',
      hoverBorder: 'hover:border-teal-400',
      gradient: 'from-teal-600 to-emerald-700',
      accent: '#0d9488',
    },
  },
  'cv-classic': {
    id: 'cv-classic',
    titleKey: 'cvClassic',
    descKey: 'cvClassic',
    category: 'cv',
    badgeText: 'الكلاسيكي',
    icon: Contact,
    colors: {
      bg: 'bg-slate-700',
      text: 'text-white',
      lightBg: 'bg-slate-100 dark:bg-slate-800',
      lightText: 'text-slate-700 dark:text-slate-300',
      border: 'border-slate-300 dark:border-slate-700',
      hoverBorder: 'hover:border-slate-500',
      gradient: 'from-slate-600 to-slate-800',
      accent: '#334155',
    },
  },
  'badge-generator': {
    id: 'badge-generator',
    titleKey: 'badgeGenerator',
    descKey: 'badgeGenerator',
    category: 'badge',
    badgeText: 'بطاقات الهوية',
    icon: Contact,
    colors: {
      bg: 'bg-pink-600',
      text: 'text-white',
      lightBg: 'bg-pink-50 dark:bg-pink-950/50',
      lightText: 'text-pink-700 dark:text-pink-400',
      border: 'border-pink-200 dark:border-pink-800',
      hoverBorder: 'hover:border-pink-400',
      gradient: 'from-pink-500 to-rose-600',
      accent: '#db2777',
    },
  },
  'text-tools': {
    id: 'text-tools',
    titleKey: 'textTools',
    descKey: 'textTools',
    category: 'text',
    icon: FileText,
    colors: {
      bg: 'bg-indigo-500',
      text: 'text-white',
      lightBg: 'bg-indigo-50 dark:bg-indigo-950/50',
      lightText: 'text-indigo-600 dark:text-indigo-400',
      border: 'border-indigo-200 dark:border-indigo-800',
      hoverBorder: 'hover:border-indigo-400',
      gradient: 'from-indigo-500 to-purple-600',
      accent: '#6366f1',
    },
  },
  'qr-generator': {
    id: 'qr-generator',
    titleKey: 'qrGenerator',
    descKey: 'qrGenerator',
    category: 'text',
    badgeText: 'باركود وQR',
    icon: QrCode,
    colors: {
      bg: 'bg-violet-600',
      text: 'text-white',
      lightBg: 'bg-violet-50 dark:bg-violet-950/50',
      lightText: 'text-violet-700 dark:text-violet-400',
      border: 'border-violet-200 dark:border-violet-800',
      hoverBorder: 'hover:border-violet-400',
      gradient: 'from-violet-600 to-purple-700',
      accent: '#7c3aed',
    },
  },
  hijri: {
    id: 'hijri',
    titleKey: 'hijri',
    descKey: 'hijri',
    category: 'text',
    badgeText: 'هجري وميلادي',
    icon: Calendar,
    colors: {
      bg: 'bg-emerald-700',
      text: 'text-white',
      lightBg: 'bg-emerald-50 dark:bg-emerald-950/50',
      lightText: 'text-emerald-800 dark:text-emerald-300',
      border: 'border-emerald-200 dark:border-emerald-800',
      hoverBorder: 'hover:border-emerald-400',
      gradient: 'from-emerald-600 to-teal-800',
      accent: '#047857',
    },
  },
  'date-calculator': {
    id: 'date-calculator',
    titleKey: 'dateCalculator',
    descKey: 'dateCalculator',
    category: 'text',
    icon: Calendar,
    colors: {
      bg: 'bg-teal-500',
      text: 'text-white',
      lightBg: 'bg-teal-50 dark:bg-teal-950/50',
      lightText: 'text-teal-700 dark:text-teal-400',
      border: 'border-teal-200 dark:border-teal-800',
      hoverBorder: 'hover:border-teal-400',
      gradient: 'from-teal-500 to-cyan-600',
      accent: '#14b8a6',
    },
  },
  'text-crypto': {
    id: 'text-crypto',
    titleKey: 'textCrypto',
    descKey: 'textCrypto',
    category: 'security',
    badgeText: 'AES-256',
    icon: Lock,
    colors: {
      bg: 'bg-emerald-600',
      text: 'text-white',
      lightBg: 'bg-emerald-50 dark:bg-emerald-950/50',
      lightText: 'text-emerald-700 dark:text-emerald-400',
      border: 'border-emerald-200 dark:border-emerald-800',
      hoverBorder: 'hover:border-emerald-400',
      gradient: 'from-emerald-600 to-teal-700',
      accent: '#059669',
    },
  },
  'word-counter': {
    id: 'word-counter',
    titleKey: 'wordCounter',
    descKey: 'wordCounter',
    category: 'text',
    badgeText: 'إحصاء فوري',
    icon: FileText,
    colors: {
      bg: 'bg-sky-600',
      text: 'text-white',
      lightBg: 'bg-sky-50 dark:bg-sky-950/50',
      lightText: 'text-sky-700 dark:text-sky-400',
      border: 'border-sky-200 dark:border-sky-800',
      hoverBorder: 'hover:border-sky-400',
      gradient: 'from-sky-500 to-indigo-600',
      accent: '#0284c7',
    },
  },
  'text-compare': {
    id: 'text-compare',
    titleKey: 'textCompare',
    descKey: 'textCompare',
    category: 'text',
    badgeText: 'كشف الفروق',
    icon: GitCompare,
    colors: {
      bg: 'bg-blue-600',
      text: 'text-white',
      lightBg: 'bg-blue-50 dark:bg-blue-950/50',
      lightText: 'text-blue-700 dark:text-blue-400',
      border: 'border-blue-200 dark:border-blue-800',
      hoverBorder: 'hover:border-blue-400',
      gradient: 'from-blue-600 to-indigo-700',
      accent: '#2563eb',
    },
  },
  'page-numbering': {
    id: 'page-numbering',
    titleKey: 'pageNumbering',
    descKey: 'pageNumbering',
    category: 'edit',
    badgeText: 'ترقيم صفحات',
    icon: FileDigit,
    colors: {
      bg: 'bg-teal-600',
      text: 'text-white',
      lightBg: 'bg-teal-50 dark:bg-teal-950/50',
      lightText: 'text-teal-700 dark:text-teal-400',
      border: 'border-teal-200 dark:border-teal-800',
      hoverBorder: 'hover:border-teal-400',
      gradient: 'from-teal-600 to-emerald-600',
      accent: '#0d9488',
    },
  },
  'text-cleaner': {
    id: 'text-cleaner',
    titleKey: 'textCleaner',
    descKey: 'textCleaner',
    category: 'text',
    badgeText: 'تنظيف فوري',
    icon: Eraser,
    colors: {
      bg: 'bg-cyan-600',
      text: 'text-white',
      lightBg: 'bg-cyan-50 dark:bg-cyan-950/50',
      lightText: 'text-cyan-700 dark:text-cyan-400',
      border: 'border-cyan-200 dark:border-cyan-800',
      hoverBorder: 'hover:border-cyan-400',
      gradient: 'from-cyan-600 to-teal-700',
      accent: '#0891b2',
    },
  },
};

// Mega menu and dropdown groupings
export const CONVERT_MENU_ITEMS: {
  toPdf: ToolId[];
  fromPdf: ToolId[];
} = {
  toPdf: ['image-to-pdf', 'stitch-images', 'cv-builder', 'text-tools'],
  fromPdf: ['pdf-to-image', 'ocr', 'id-photo', 'pdf-grayscale'],
};

export const BUSINESS_MENU_ITEMS: ToolId[] = [
  'payroll',
  'clearance',
  'invoice',
  'voucher',
  'vat-calculator',
  'tafqeet',
];

export const MEGA_MENU_COLUMNS: {
  title: string;
  iconBg: string;
  tools: ToolId[];
}[] = [
  {
    title: 'تنظيم وتجميع PDF',
    iconBg: 'bg-red-500',
    tools: ['merge', 'split', 'rotate', 'organize', 'nup', 'stamp-remover'],
  },
  {
    title: 'تحويل واستخراج الصور',
    iconBg: 'bg-amber-500',
    tools: [
      'image-to-pdf',
      'pdf-to-image',
      'ocr',
      'id-photo',
      'stitch-images',
      'social-crop',
      'image-tools',
      'image-watermark',
    ],
  },
  {
    title: 'تعديل وأمان المستندات',
    iconBg: 'bg-purple-600',
    tools: [
      'edit',
      'compress',
      'protect',
      'page-numbering',
      'text-crypto',
      'redact',
      'sign',
      'watermark',
      'metadata-cleaner',
      'pdf-grayscale',
    ],
  },
  {
    title: 'الأعمال والمالية والرواتب',
    iconBg: 'bg-emerald-600',
    tools: [
      'payroll',
      'clearance',
      'invoice',
      'voucher',
      'vat-calculator',
      'tafqeet',
    ],
  },
  {
    title: 'السير الذاتية والنصوص والمعاملات',
    iconBg: 'bg-blue-600',
    tools: [
      'cv-builder',
      'word-counter',
      'text-compare',
      'text-cleaner',
      'text-tools',
      'badge-generator',
      'qr-generator',
      'hijri',
      'date-calculator',
      'search-text',
    ],
  },
];
